language: python
python:
  - '2.7'
addons:
  postgresql: 9.3
cache:
  apt: true
  directories:
    - $HOME/.pip-cache/
before_install:
  - gem install sass
  - npm install
env:
  - PIP_DOWNLOAD_CACHE=$HOME/.pip-download-cache
  - DJANGO_DEBUG=False
  - DJANGO_SECRET_KEY=ZGtvYm90cmF2aXM
install:
  - pip install -r requirements.txt --use-mirrors
  - python manage.py syncdb --noinput --settings=dkobo.settings
  - python manage.py migrate --noinput --settings=dkobo.settings
notifications:
  irc: 'irc.freenode.org#kobotest'
